#docker-compose version
version: '3'

#list of containers
services:

  #------------------------------------#
  #               NGINX                #
  #------------------------------------#
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  #------------------------------------#
  #              MARIADB               #
  #------------------------------------#
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  #------------------------------------#
  #              WORDPRESS             #
  #------------------------------------#
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb

  #------------------------------------#
  #              PORTAINER             #
  #------------------------------------#
  portainer:
    container_name: portainer
    networks:
      - inception
    build:
      context: ./requirements/bonus/portainer
      dockerfile: ./Dockerfile
      args:
        PORT_PWD: ${PORT_PWD}
    image: portainer
    ports:
      - 8000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - .env

  #------------------------------------#
  #               ADMINER              #
  #------------------------------------#
  adminer:
    container_name: adminer
    networks:
      - inception
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    expose:
      - 9000
    depends_on:
      - mariadb

  #------------------------------------#
  #               REDIS                #
  #------------------------------------#
  redis:
    container_name: redis
    networks:
      - inception
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    ports:
      - 6379:6379
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

  ftp:
    container_name: ftp
    networks:
      - inception
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    ports:
      - 21:21
      - 20:20
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env

#volumes
volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rsabbah/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rsabbah/data/wordpress
      o: bind
      
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rsabbah/data/portainer
      o: bind

#network configuration
networks:
  inception:
    driver: bridge
