#docker-compose version
version: '3'

#list of containers
services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx
    ports:
      - 443:443

  portainer:
    container_name: portainer
    networks:
      - inception
    build:
      context: ./requirements/bonus/portainer
      dockerfile: ./Dockerfile
      args:
        PORT_PWD: ${PORT_PWD}
    image: portainer
    ports:
      - 8000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - .env

volumes:
  portainer_data:

#network configuration
networks:
  inception:
    driver: bridge
